# Generated by Django 6.0.2 on 2026-02-04 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Trending', 'Trending'), ('Breaking', 'Breaking'), ('New', 'New'), ('Politics', 'Politics'), ('Sports', 'Sports'), ('Finance', 'Finance'), ('Crypto', 'Crypto'), ('Tech', 'Tech'), ('Culture', 'Culture')], default='Trending', max_length=50)),
                ('volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('endDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('change24h', models.FloatField(default=0.0)),
                ('winner_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('probability', models.FloatField(default=50.0)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='api.market')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.DecimalField(decimal_places=8, max_digits=20)),
                ('avgPrice', models.FloatField()),
                ('side', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=3)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.market')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.outcome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=10)),
                ('tier', models.CharField(choices=[('TIER_1', 'Tier 1'), ('TIER_2', 'Tier 2'), ('TIER_3', 'Tier 3')], default='TIER_1', max_length=10)),
                ('avatarUrl', models.URLField(blank=True, null=True)),
                ('joinedDate', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('shares', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.FloatField()),
                ('totalValue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=10)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
