# Generated by Django 6.0.2 on 2026-02-05 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'permissions': [('can_seed_liquidity', 'Can inject initial market capital'), ('can_resolve_market', 'Can finalize market outcomes'), ('can_halt_trading', 'Can pause a market during extreme volatility')]},
        ),
        migrations.AddField(
            model_name='market',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_markets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='market',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_markets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_MARKET', 'Create Market'), ('RESOLVE_MARKET', 'Resolve Market'), ('SEED_LIQUIDITY', 'Seed Liquidity'), ('HALT_TRADING', 'Halt Trading'), ('CANCEL_ORDER', 'Cancel Order'), ('VIEW_SENSITIVE', 'View Sensitive Data'), ('OTHER', 'Other')], max_length=50)),
                ('target_object', models.CharField(help_text='String representation of the object being acted upon', max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
