# Generated by Django 6.0.2 on 2026-02-05 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_market_options_market_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.outcome'),
        ),
    ]
