# Generated by Django 6.0.2 on 2026-02-06 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trade_outcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_MARKET', 'Create Market'), ('RESOLVE_MARKET', 'Resolve Market'), ('SEED_LIQUIDITY', 'Seed Liquidity'), ('HALT_TRADING', 'Halt Trading'), ('CANCEL_ORDER', 'Cancel Order'), ('VIEW_SENSITIVE', 'View Sensitive Data'), ('BAN_USER', 'Ban User'), ('UNBAN_USER', 'Unban User'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
