# Generated by Django 5.0.10 on 2026-02-06 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_ban_reason_profile_banned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_MARKET', 'Create Market'), ('RESOLVE_MARKET', 'Resolve Market'), ('SEED_LIQUIDITY', 'Seed Liquidity'), ('HALT_TRADING', 'Halt Trading'), ('CANCEL_ORDER', 'Cancel Order'), ('VIEW_SENSITIVE', 'View Sensitive Data'), ('BAN_USER', 'Ban User'), ('UNBAN_USER', 'Unban User'), ('REQUEST_ACCESS', 'Request Group Access'), ('APPROVE_ACCESS', 'Approve Group Access'), ('DENY_ACCESS', 'Deny Group Access'), ('ADD_GROUP_MARKET', 'Add Market to Group'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='market',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Business', 'Business'), ('Finance', 'Finance'), ('Sports', 'Sports'), ('Crypto', 'Crypto'), ('Politics', 'Politics'), ('Other', 'Other')], default='Other', max_length=50)),
                ('privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('INVITE', 'Invite Only')], default='INVITE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='member_groups', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_manage_groups', 'Can manage groups'), ('can_approve_access', 'Can approve group access')],
            },
        ),
        migrations.CreateModel(
            name='GroupAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('message', models.TextField(blank=True, help_text="User's message with access request", null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='api.group')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_access_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_markets', to='api.group')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_groups', to='api.market')),
            ],
            options={
                'unique_together': {('group', 'market')},
            },
        ),
    ]
